include ../common/config.mk

CFILES := $(CFILES) ../bloomGameId/bloom_game_id.c

TARGET = playActivity
CFLAGS := $(CFLAGS) -D_DEFAULT_SOURCE
LDFLAGS := $(LDFLAGS) -lsqlite3

include ../common/commands.mk
include ../common/recipes.mk
