include ../common/config.mk

CFILES := $(CFILES) ../playActivity/playActivityModel.c

TARGET = playActivityUI
LDFLAGS := $(LDFLAGS) -lSDL -lSDL_image -lSDL_ttf -lsqlite3

include ../common/commands.mk
include ../common/recipes.mk
