name: Check build
on:
  merge_group:
  pull_request:
    paths-ignore:
      - '**/README.md'
      - 'website/'

permissions:
  contents: read

jobs:
  build:
    name: Check build
    runs-on: ubuntu-latest
    container:
      image: aemiii91/miyoomini-toolchain@sha256:e5123590ad75d27f0f4c91196e3119a255cad45f3ae15243e29a8e0a2ec50132
      options: --user root
    steps:
    - name: Checkout repository
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      with:
        submodules: recursive
    - name: Build
      shell: bash
      run: |
        source /root/.bashrc
        make build
