name: Check build
on:
  merge_group:
  pull_request:
    paths-ignore:
      - '**/README.md'
      - 'website/'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Check build
    runs-on: ubuntu-latest
    container:
      image: aemiii91/miyoomini-toolchain@sha256:e5123590ad75d27f0f4c91196e3119a255cad45f3ae15243e29a8e0a2ec50132
      options: --user root
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        submodules: recursive
    - name: Build
      shell: bash
      run: |
        source /root/.bashrc
        make build
