name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'website/**/*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'website'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
      - uses: webfactory/ssh-agent@6b2f2c5354ff41f1edbbf7a17ea9b6178c89be9f # v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        run: |
          git config --global user.email "44569252+Aemiii91@users.noreply.github.com"
          git config --global user.name "Aemiii91"
          yarn install --frozen-lockfile
          yarn deploy
